# Generated by Django 5.2.5 on 2025-08-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('type', models.CharField(choices=[('mental', 'Mental Health'), ('rehab', 'Rehabilitation')], max_length=10)),
                ('county', models.CharField(max_length=50)),
                ('subcounty', models.CharField(max_length=50)),
                ('constituency', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=50)),
            ],
        ),
    ]
