# Generated by Django 5.2.5 on 2026-03-25 18:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('mental_health', 'Mental Health'), ('rehab', 'Rehabilitation')], help_text='Type of healthcare facility', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('operating_time', models.CharField(help_text='e.g. 8:00 AM - 5:00 PM', max_length=100)),
                ('patient_care_setting', models.CharField(choices=[('Inpatient', 'Inpatient'), ('Outpatient', 'Outpatient'), ('Inpatient, Outpatient', 'Inpatient and Outpatient')], max_length=100)),
                ('modes_of_payment', models.CharField(help_text='e.g. Cash, M-Pesa, Card', max_length=255)),
                ('insurance_accepted', models.TextField(help_text='List of accepted insurance providers')),
                ('operating_days', models.CharField(help_text='e.g. Monday - Friday', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Healthcare Facility',
                'verbose_name_plural': 'Healthcare Facilities',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('org_name', models.CharField(max_length=255, verbose_name='Name of Organization')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('contact_person', models.CharField(max_length=150, verbose_name='Contact Person')),
                ('correspondence_phone', models.CharField(max_length=30, verbose_name='Correspondence Number')),
                ('correspondence_email', models.EmailField(max_length=254, verbose_name='Correspondence Email')),
                ('hear_about_us', models.CharField(choices=[('internet', 'Internet Search'), ('social', 'Social Media'), ('direct', 'Direct Mail or Physical Advertisement'), ('referral', 'Referral'), ('news', 'News Article'), ('event', 'Event or Conference'), ('other', 'Other')], default='referral', max_length=20, verbose_name='How did you hear about us?')),
                ('hear_about_us_other', models.CharField(blank=True, max_length=255, verbose_name='If Other, please specify')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_orgs', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Organization')),
                ('public_email', models.EmailField(max_length=254, verbose_name='Public Contact Email')),
                ('contact_number_1', models.CharField(max_length=30, verbose_name='Contact Number 1')),
                ('contact_number_2', models.CharField(blank=True, max_length=30, verbose_name='Contact Number 2')),
                ('contact_number_3', models.CharField(blank=True, max_length=30, verbose_name='Contact Number 3')),
                ('year_founded', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year Founded')),
                ('registration_status', models.CharField(blank=True, choices=[('formal', 'Formal'), ('informal', 'Informal')], max_length=10, verbose_name='Registration Status')),
                ('year_formally_registered', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year Formally Registered')),
                ('country_of_registration', models.CharField(default='Kenya', max_length=100, verbose_name='Country of First Registration')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='facility_logos/', verbose_name='Organization Logo')),
                ('website', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter / X')),
                ('facebook', models.URLField(blank=True)),
                ('whatsapp', models.URLField(blank=True, verbose_name='WhatsApp Group')),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('org_type', models.CharField(blank=True, choices=[('intl_ngo', 'International NGO'), ('local_ngo', 'Local NGO'), ('cbo', 'Community-Based Org'), ('coalition', 'Coalition'), ('network', 'Network'), ('other', 'Other')], max_length=15, verbose_name='Type of Organization')),
                ('county', models.CharField(max_length=100, verbose_name='County')),
                ('sub_county', models.CharField(max_length=100, verbose_name='Sub-County')),
                ('funding_source', models.CharField(blank=True, choices=[('local', 'Local (≥50%)'), ('foreign', 'Foreign (≥50%)'), ('mixed', 'Mixed')], max_length=10, verbose_name='Main Funding Sources')),
                ('is_youth_org', models.BooleanField(null=True, verbose_name='Youth Organization?')),
                ('youth_type', models.CharField(blank=True, choices=[('led', 'Youth-led'), ('serving', 'Youth-serving'), ('both', 'Youth-led & Youth-serving')], max_length=10, verbose_name='Youth Type')),
                ('is_disability_org', models.BooleanField(null=True, verbose_name='Organization for Persons with Disabilities?')),
                ('is_female_led', models.BooleanField(null=True, verbose_name='Female-led?')),
                ('areas_of_intervention', models.JSONField(default=list, help_text='List of AreaOfIntervention values e.g. ["health", "mental_health"]', verbose_name='Areas of Intervention')),
                ('mh_focus_areas', models.JSONField(default=list, help_text='List of MHFocusArea values e.g. ["promotive", "curative"]', verbose_name='MH Focus Areas')),
                ('mh_service_categories', models.JSONField(default=list, help_text='List of MHServiceCategory values e.g. ["psychotherapy", "psychiatry"]', verbose_name='MH Service Categories')),
                ('achievements', models.TextField(blank=True, verbose_name='Achievements & Key Milestones')),
                ('persons_reached', models.PositiveIntegerField(blank=True, null=True, verbose_name='No. of Persons Reached')),
                ('mh_funding_used_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='MH Funding Used (KES)')),
                ('advertise_tier', models.CharField(choices=[('none', 'Free (no ad)'), ('basic', 'Basic – $25/mo'), ('premium', 'Premium – $60/mo')], default='none', max_length=10, verbose_name='Advertise on Platform')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='e.g. -1.292100 for Nairobi', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='e.g. 36.821900 for Nairobi', max_digits=9, null=True, verbose_name='Longitude')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('registration_certificate', models.FileField(blank=True, null=True, upload_to='facility_docs/', verbose_name='Registration Certificate')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_facilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
