# Generated by Django 5.2.5 on 2026-03-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthcareFacility',
        ),
    ]
