# Generated by Django 5.2.5 on 2026-02-03 18:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('mental_health', 'Mental Health'), ('rehab', 'Rehabilitation')], help_text='Type of healthcare facility', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('operating_time', models.CharField(help_text='e.g. 8:00 AM - 5:00 PM', max_length=100)),
                ('patient_care_setting', models.CharField(choices=[('Inpatient', 'Inpatient'), ('Outpatient', 'Outpatient'), ('Inpatient, Outpatient', 'Inpatient and Outpatient')], max_length=100)),
                ('modes_of_payment', models.CharField(help_text='e.g. Cash, M-Pesa, Card', max_length=255)),
                ('insurance_accepted', models.TextField(help_text='List of accepted insurance providers')),
                ('operating_days', models.CharField(help_text='e.g. Monday - Friday', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Healthcare Facility',
                'verbose_name_plural': 'Healthcare Facilities',
            },
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
